# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.runs/synth_1/riscv_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param synth.incrementalSynthesisCache C:/Users/gt111/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-7152-Gaurav/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.cache/wt [current_project]
set_property parent.project_path C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/ALU.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/HazardUnit.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/adder.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/aludec.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/controller.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/dmem.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/ex_stage.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/extend.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/flopenr.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/flopenrc.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/flopr.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/floprc.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/id_stage.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/if_stage.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/imem.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/maindec.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/mem_stage.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/mux2.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/mux3.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/regfile.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/wb_stage.sv
  C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/sources_1/new/riscv_top.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/gt111/RISC_V_single_cycle/RISC_V_single_cycle.srcs/utils_1/imports/synth_1/controller.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top riscv_top -part xc7a35ticpg236-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
